Drakkar-Software/OctoBot-Evaluators

octobot_evaluators/api/evaluators.py
octobot_evaluators/api/inspection.py

now check if evaluator is enabled or not before creating it

restore evaluator enable check at startup

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/api/evaluators.py
octobot_evaluators/evaluator/abstract_evaluator.py

Requires #12 and https://github.com/Drakkar-Software/OctoBot-Trading/pull/56
Related to https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/12#discussion_r362324310

[AbstractEvaluator] Add cryptocurrency support

---

demo.py
octobot_evaluators/channels/matrix.py
octobot_evaluators/data/matrix.pxd
octobot_evaluators/data/matrix.py
octobot_evaluators/evaluator/strategy_evaluator.py
tests/channels/test_matrix.py

resolves #7
related to https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/100
and https://github.com/Drakkar-Software/OctoBot-Trading/pull/64

Add cryptocurrency parameter in matrix callback #7

---

CHANGELOG.md
README.md
demo.py
octobot_evaluators/__init__.py
octobot_evaluators/api/evaluators.py
octobot_evaluators/channels/matrix.py
octobot_evaluators/data/matrix.pxd
octobot_evaluators/data/matrix.py
octobot_evaluators/evaluator/abstract_evaluator.py
octobot_evaluators/evaluator/strategy_evaluator.py
octobot_evaluators/matrices/__init__.pxd
octobot_evaluators/matrices/__init__.py
octobot_evaluators/matrices/matrices.pxd
octobot_evaluators/matrices/matrices.py
setup.py
tests/channels/test_matrix.py
tests/matrices/__init__.py
tests/matrices/test_matrices.py

Should also resolve https://github.com/Drakkar-Software/OctoBot-Evaluators/issues/17

[Matrix] migrate matrix singleton to multiple matrices 

---

octobot_evaluators/evaluator/TA_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/71
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/75

[ExchangeChannels] Use exchange id

---

demo.py
octobot_evaluators/api/__init__.py
octobot_evaluators/evaluator/__init__.py
tests/channels/test_matrix.py
tests/matrices/test_matrices.py

Remove wildcard imports

---

octobot_evaluators/api/evaluators.py
octobot_evaluators/channels/matrix.py
octobot_evaluators/evaluator/abstract_evaluator.py
octobot_evaluators/evaluator/social_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/19

update exception logger 

---

octobot_evaluators/api/evaluators.py
octobot_evaluators/api/initialization.py
octobot_evaluators/api/inspection.py
octobot_evaluators/constants.py
octobot_evaluators/evaluator/TA_evaluator.py
octobot_evaluators/evaluator/abstract_evaluator.py
octobot_evaluators/evaluator/abstract_util.py
octobot_evaluators/evaluator/realtime_evaluator.py
octobot_evaluators/evaluator/social_evaluator.py
octobot_evaluators/evaluator/strategy_evaluator.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/28

tentacle manager integration 

---

CHANGELOG.md
README.md
demo.py
octobot_evaluators/__init__.py
octobot_evaluators/api/evaluators.py
octobot_evaluators/api/initialization.py
octobot_evaluators/api/inspection.py
octobot_evaluators/channels/__init__.py
octobot_evaluators/channels/matrix.py
octobot_evaluators/constants.py
octobot_evaluators/evaluator/abstract_evaluator.py
octobot_evaluators/evaluator/abstract_util.py
octobot_evaluators/evaluator/strategy_evaluator.py
requirements.txt
tests/channels/test_matrix.py

Fix imports 

---

octobot_evaluators/api/evaluators.py
octobot_evaluators/evaluator/TA_evaluator.py
octobot_evaluators/evaluator/abstract_evaluator.py
octobot_evaluators/evaluator/realtime_evaluator.py
octobot_evaluators/evaluator/social_evaluator.py
octobot_evaluators/evaluator/strategy_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/14

tentacles migration adaptations 

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt

[Version] v1.4.6

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/evaluator/TA_evaluator.py
requirements.txt

[Version] v1.4.8

---

octobot_evaluators/data/matrix.pxd
octobot_evaluators/data/matrix.py
octobot_evaluators/data_manager/matrix_manager.pxd
octobot_evaluators/data_manager/matrix_manager.py
requirements.txt
tests/data_manager/test_matrix_manager.py

Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/42

[MatrixManager] Add node expiration management 

---

CHANGELOG.md
README.md
demo.py
octobot_evaluators/__init__.py
octobot_evaluators/api/evaluators.py
octobot_evaluators/api/initialization.py
octobot_evaluators/channels/__init__.py
octobot_evaluators/channels/evaluator_channel.pxd
octobot_evaluators/channels/evaluator_channel.py
octobot_evaluators/channels/evaluators.pxd
octobot_evaluators/channels/evaluators.py
octobot_evaluators/channels/matrix.py
octobot_evaluators/constants.py
octobot_evaluators/data_manager/matrix_manager.py
octobot_evaluators/evaluator/TA_evaluator.py
octobot_evaluators/evaluator/abstract_evaluator.py
octobot_evaluators/evaluator/social_evaluator.py
octobot_evaluators/evaluator/strategy_evaluator.py
requirements.txt
setup.py
tests/channels/test_matrix.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/52
- [Channels] Evaluators channel
- Matrix event clear management
- Matrix node value expiration
- [Channels] get_chan api with a new matrix_id param

[Version] v1.5.0  

---

README.md

[![Coverage Status](https://coveralls.io/repos/github/Drakkar-Software/OctoBot-Evaluators/badge.svg)](https://coveralls.io/github/Drakkar-Software/OctoBot-Evaluators)

[Readme] Add coverage badge  

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/api/initialization.py
octobot_evaluators/channels/evaluator_channel.py
octobot_evaluators/channels/evaluators.py
octobot_evaluators/channels/matrix.py
octobot_evaluators/evaluator/TA_evaluator.py
octobot_evaluators/evaluator/abstract_evaluator.py
octobot_evaluators/evaluator/strategy_evaluator.py
requirements.txt

Depends on https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/59

[Channel] Add synchronized support 

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/data_manager/matrix_manager.py
octobot_evaluators/evaluator/strategy_evaluator.py
requirements.txt
tests/data_manager/test_matrix_manager.py

- [EventTree] Remove event related methods in matrix_manager

[Version] v1.5.4  

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/api/initialization.py

- [API] Initialization incorrect type

Fix initialization api

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt

- [Requirements] requirements update

[Version] v1.5.7

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/evaluator/strategy_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/188

backtesting fixes

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/channels/evaluator_channel.py
requirements.txt

- [EvaluatorChannel] Default priority level to medium

[Version] v1.5.10

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/evaluator/abstract_evaluator.py

- [AbstractEvaluator] Priority level

[AbstractEvaluator] Fix priority level

---

CHANGELOG.md
README.md
octobot_evaluators/consumers/__init__.pxd
octobot_evaluators/consumers/__init__.py
octobot_evaluators/consumers/octobot_channel_consumer.pxd
octobot_evaluators/consumers/octobot_channel_consumer.py
requirements.txt
setup.py

- [OctoBotChannel] Add consumer

[Version] v1.5.12

---

CHANGELOG.md
Makefile
octobot_evaluators/__init__.py
requirements.txt
setup.py

[Version] v1.5.13

---

CHANGELOG.md
octobot_evaluators/__init__.py
octobot_evaluators/evaluator/TA_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/221
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/222

get last candle as list for re-evaluation triggers

---

CHANGELOG.md
README.md
demo.py
octobot_evaluators/__init__.py
octobot_evaluators/api/evaluators.py
octobot_evaluators/api/initialization.py
octobot_evaluators/api/inspection.py
octobot_evaluators/consumers/octobot_channel_consumer.py
tests/api/test_evaluators.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/88

Remove advanced manager

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt
setup.py

[Version] v1.5.16

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt
setup.py

[Version] v1.5.19

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt
setup.py

[Version] v1.5.21

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt
setup.py

- Requirements
Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/103
Depends on https://github.com/Drakkar-Software/OctoBot-Channels/pull/54

[Version] v1.5.22

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/api/initialization.py
octobot_evaluators/api/inspection.py
octobot_evaluators/evaluators/TA_evaluator.py
octobot_evaluators/evaluators/abstract_evaluator.py
octobot_evaluators/evaluators/evaluator_factory.py
octobot_evaluators/evaluators/realtime_evaluator.py
octobot_evaluators/evaluators/social_evaluator.py
octobot_evaluators/evaluators/strategy_evaluator.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/145

enable profiles

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt
setup.py
tests/requirements/test_tulipy.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/151

add tulipy tests

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt
setup.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/153

Bump requirements

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt
setup.py

[Version] v1.6.14

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/evaluators/TA_evaluator.py
octobot_evaluators/octobot_channel_consumer.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/592

[TA] can now use real time time frame if necessary

---

octobot_evaluators/api/__init__.py
octobot_evaluators/api/evaluators.py
octobot_evaluators/api/initialization.py
octobot_evaluators/evaluators/abstract_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/210 in version

[HistoricalCandles] handle historical candles config

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
requirements.txt
tests/evaluators/test_evaluator_factory.py
tests/evaluators/test_evaluator_factory_create_evaluators.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/246

[Symbols] symbols update

---

octobot_evaluators/matrix/matrix.pxd
octobot_evaluators/matrix/matrix.py
octobot_evaluators/matrix/matrix_manager.pxd

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/275

[Tree] migrate event_tree to base_tree

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/evaluators/strategy_evaluator.py

fix strategy stop (is currently preventing strategy optimizer stop)

fix strategy stop

---

CHANGELOG.md
README.md
octobot_evaluators/__init__.py
octobot_evaluators/evaluators/scripted_evaluator.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/322

Trigger source

---

README.md

Tried to update README file according to issue, however, needs your guidance in this case. The PR closes #56

docs: Update README for Module Manager
